package com.mindmatrix.shishusneh.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * GrowthRecord — Tracks Baby's Growth Measurements
 *
 * Each row represents ONE measurement session (e.g., a doctor visit
 * or a home weigh-in). Over time these records form the growth chart.
 *
 * TABLE STRUCTURE:
 * ┌────┬─────────────┬──────────┬──────────┬──────────┬───────────────────┬───────┬───────────┐
 * │ id │ babyProfileId│ date     │ weightKg │ heightCm │ headCircumferenceCm│ notes │ createdAt │
 * ├────┼─────────────┼──────────┼──────────┼──────────┼───────────────────┼───────┼───────────┤
 * │ 1  │ 1           │ 17446..  │ 3.2      │ 49.5     │ 34.0              │       │ 17145..   │
 * │ 2  │ 1           │ 17472..  │ 4.1      │ 52.0     │ 36.5              │ fed   │ 17172..   │
 * └────┴─────────────┴──────────┴──────────┴──────────┴───────────────────┴───────┴───────────┘
 *
 * UNITS:
 * - Weight is always stored in KILOGRAMS (metric)
 * - Height is always stored in CENTIMETERS (metric)
 * - Head circumference is always stored in CENTIMETERS (metric)
 * - Imperial display is done via UnitConverter at the UI layer
 */
@Entity(tableName = "growth_records")
data class GrowthRecord(

    // Unique identifier — auto-generated by Room
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    // Links this record to a specific baby profile
    // In this app we only have one baby, but this future-proofs for siblings
    val babyProfileId: Int,

    // When this measurement was taken (epoch milliseconds)
    // Stored as Long because Room can't handle Date objects directly
    val date: Long,

    // Weight in kilograms (e.g., 3.2f for 3.2 kg)
    val weightKg: Float,

    // Height/Length in centimeters (e.g., 49.5f for 49.5 cm)
    val heightCm: Float,

    // Head circumference in centimeters (OPTIONAL — can be null)
    // Most pediatricians track this for the first 2 years
    val headCircumferenceCm: Float? = null,

    // Optional notes (e.g., "After morning feed", "Doctor's visit")
    val notes: String = "",

    // When this record was created in the app
    val createdAt: Long = System.currentTimeMillis()
)
